### ISSUE TITLE
JSON responses should be Content-Type: application/json

### ISSUE THREAD

**Issue by will-moore** [ome/omero_search_engine_client#3]
All API end-points for loading JSON should be a JSON dict (not a list) with Content-Type: application/json
so that they appear as valid JSON to clients.
E.g. opening this in my browser, with a JSON extension installed should render it as JSON, but this fails as it's "text/html"

/searchengine/serachusingvaluesonly/?value=pdx1&resource=image

For dicts, instead of
```
return json.dumps(dict)
```
It looks like flask will use `Content-Type:application/json` if you simply do:
```
return dict
```
But for lists, you need to wrap it in a dict, which will be a breaking change for clients, e.g:
```
return {"data": my_list}
```

**Comment by khaledk2** [comment]
I will replace json.dumps with jsonify which is a flask helper method that returns a response (serialize the data to a JSON ) with the content-type header "application/json"
