### ISSUE TITLE
search values with Key and Value for autocomplete

### ISSUE THREAD

**Issue by will-moore** [ome/omero_search_engine_client#7]
I'm using this endpoint to provide auto-complete for "Any" value
`serachusingvaluesonly/?value=pdx&resource=image`

<img width="278" alt="Screenshot 2022-04-07 at 15 52 40" src="https://user-images.githubusercontent.com/900055/162228046-e76019ec-984a-4443-9f7f-e8049eb97693.png">

which is nice as it gives counts for the results.
(also at https://github.com/ome/omero_search_engine_client/pull/4)

```
{
"results": [
  {
    "Attribute": "Gene Symbol",
    "Number of images": 1039,
    "Value": "pdxdc1"
  },
```

But when it comes to auto-complete for a particular key, we use:
`get_values/?key=Gene%20Symbol&resource=image`
which doesn't filter by any value and doesn't have any counts.

It would be nice to have an endpoint like `serachusingvaluesonly` but using "key" too.

**Comment by khaledk2** [comment]
There is an endpoint  (`serachforvaluesusingkey`) that returns what you want, 
For example, to get the available values for the `Organism` attribute, you can use this link:
`https://idr-testing.openmicroscopy.org/searchengine/serachforvaluesusingkey/?key=Organism&&resource=image`

**Comment by khaledk2** [comment]
It has a typo fix and should be `searchforvaluesusingkey`

**Comment by will-moore** [comment]
Ah - OK, I see that has the counts, but it doesn't allow me to filter by Value, so it's not going to work for autocomplete.
E.g. https://idr-testing.openmicroscopy.org/searchengine/searchforvaluesusingkey/?key=Compound%20Name&&resource=image has `1856590` items, but only the first 9999 are returned so I can't filter in the JS code.

**Comment by will-moore** [comment]
Moved this to https://github.com/ome/omero_search_engine/issues/11
